### ISSUE TITLE
Interactive Feedback

### ISSUE THREAD

**Issue by dyburke** [synap5e/overtrack-web#14]
Hi, subscribed to overtrack.gg right now; great application, thank you!

It would be very nice, however, to be able to report bugs that I see on the site itself instead of tracking down the github. I'd like to suggest something similar to https://usersnap.com/ where a user can highlight a portion of the page and report an issue. Something simple that just takes a picture, let's the user comment would be awesome and help report issues with the graphing.

Maybe not worth the effort for you, as this likely isn't your fulltime job, but just an idea. :)

**Comment by teamcoltra** [comment]
I like to think their company is called "Users Nap" where it helps you find a good place to nap, they also help with bug reports. 

While maybe not this app, I do think a link to the issue tracker might be useful.

**Comment by synap5e** [comment]
Sorry about no response here.
I think this should be somewhat covered by #35 for issues with the tracking itself.
For design issues, with the help of some of the great people helping out now hopefully some of the design issues with the site will now be resolved 😄. Perhaps this could be something to revisit once the site is in a bit better state.
