### ISSUE TITLE
Getting started section, button padding missing

### ISSUE THREAD

**Issue by benolot** [synap5e/overtrack-web#20]
In latest chrome on windows 10 PC, visit https://overtrack.gg/tracker

Notice the download client button, it's missing some padding beneath it causing it to fit uncomfortably close to the text. 

![image](https://user-images.githubusercontent.com/2461562/56617225-391d1900-6617-11e9-9ee8-31fba1031b81.png)

**Comment by zsol** [comment]
This is no longer the case.
![image](https://user-images.githubusercontent.com/66740/58704213-25499d00-83a3-11e9-9538-64c886505171.png)
