### ISSUE TITLE
Season selection button arrow misaligned

### ISSUE THREAD

**Issue by benolot** [synap5e/overtrack-web#24]
Goto a page with a season selection button on it, such as the /winrates page as a signed in subscriber.

On latest chrome on a windows 10 PC, you can see the arrow in the season selection button is misaligned vertically.

![image](https://user-images.githubusercontent.com/2461562/56617768-8e0d5f00-6618-11e9-932b-5a87bc596648.png)

I'm also curious as to other peoples thoughts regarding why the text is in a blue box by itself and if we should also change that?

**Comment by teamcoltra** [comment]
This was one of those things in the new design I thought "I don't know why he did that in the first place, but obviously he had to go out of his way to do it, so I'll trust there was a reason for it" and left it. :P

**Comment by benolot** [comment]
This needs discussion regarding whether or not we want to keep the blue background.

**Comment by teamcoltra** [comment]
+1 ditch blue background

**Comment by synap5e** [comment]
@teamcoltra 
> I don't know why he did that in the first place
It wasn't a conscious decision, just how the multiselect dropdown library worked. 
I had a few troubles making it work exactly how I wanted, and as a result there are probably a few hacks I did to get it working.

I'm all good with whatever design changes we go for, up to and including replacing the dropdown system if it seems necessary.

**Comment by benolot** [comment]
So to confirm, we're going to remove the blue background from text and fix the alignment as part of this issue?
