### ISSUE TITLE
Fix season selection for winrates

### ISSUE THREAD

**Issue by synap5e** [synap5e/overtrack-web#30]
The games list API has changed to allow season query, and by default includes only the latest season. The new endpoint is https://api2.overtrack.gg/overwatch/games which now also returns a list of valid seasons e.g. for a dropdown. A different season can be queried with e.g. https://api2.overtrack.gg/overwatch/games?season=season%205
The winrates page now uses the new games list API, but does not populate the dropdown or fetch older seasons. 

Alternatively we might want to redo winrates page entirely...

**Comment by teamcoltra** [comment]
We do want to redo winrates page, but honestly I think we can make the minor fixes now. It seems we want to redo everything at some point.

**Comment by synap5e** [comment]
I'll leave it open to whoever picks up the banner on this issue whether they choose to fix or redo then 😝

**Comment by benolot** [comment]
Is this ready to be fixed @synap5e ?

**Comment by synap5e** [comment]
Yep.
This is one of the higher priority issues right now, especially with the new season meaning people can't access winrates for the last season anymore. I'll be happy with either the API fix or a redesign depending on what people want to tackle (and how much the current design upsets them 😉 )

**Comment by benolot** [comment]
Then I'll pin it and mark as ready.
