### ISSUE TITLE
Add link to overtrack-web repo

### ISSUE THREAD

**Issue by synap5e** [synap5e/overtrack-web#34]
It might be nice to directly link this repo on the site somewhere. 
Perhaps in the footer next to "Join our Discord"

![image](https://user-images.githubusercontent.com/2515062/56778965-03517d80-682d-11e9-9e29-98a8b71be95e.png)

**Comment by teamcoltra** [comment]
Sure, Join Our Discord | Fork This Site

**Comment by benolot** [comment]
This has now been fixed, closing.
