### ISSUE TITLE
Add Havana map images

### ISSUE THREAD

**Issue by synap5e** [synap5e/overtrack-web#48]

**Comment by benolot** [comment]
@synap5e can you provide the sizes needed?

**Comment by synap5e** [comment]
@benolot
Small images are 320x110 
e.g. https://github.com/synap5e/overtrack-web/blob/master/src/assets/images/maps/ilios.jpg

Banner images are 2600x360
e.g. https://github.com/synap5e/overtrack-web/blob/master/src/assets/images/maps/ilios-banner.jpg

Both are cropped and resized from the loading map image
