### ISSUE TITLE
Update dependancies to fix tar security vulnerability

### ISSUE THREAD

**Issue by synap5e** [synap5e/overtrack-web#49]
tar before 4.4.2 has a file overwrite issue, so I get this lovely alert whenever I go to github
![image](https://user-images.githubusercontent.com/2515062/57437829-b5119500-7296-11e9-974d-62152af9e89c.png)

I believe we are currently waiting on https://github.com/nodejs/node-gyp/issues/1714 as this has a dependency on the old tar

**Comment by benolot** [comment]
@synap5e this fix may wait a while. You can dismiss the vulnerability alert and mark it as can't currently fix iirc. I've had to do that on a lot of repos until the node ecosystem organises itself.

**Comment by synap5e** [comment]
👍 dismissed - I'll leave the issue up as a reminder though
